// AUTO-GENERATED by scripts/gen-criteria.mjs from skill/engine/criteria.json — DO NOT EDIT.
// 判据唯一事实源 = skill/engine/criteria.json；改判据请改注册表后重跑生成器（scripts/check-criteria.mjs 机检一致）。

export const CRITERIA_VERSION = "v2.0.0"

/** 摄取域判据段（拼进 DEFAULT_DISTILL_PROMPT） */
export const INGEST_JUDGE = [
  "第一层归属路由（对每条候选按序判定）：",
  "- R1 泛化方向指引？这条知识的作用=下次做类似任务给大概方向？→ route=memory（粗粒度是特性，不要把细节条文塞进记忆库）",
  "- R2 官方规范/平台规则/工具用法等**跨项目有用**的细粒度条文 → route=memory（归 notes/tools 或 notes/lessons，教程式浓缩）",
  "- R3 某项目专属事实（项目结构/该项目用户拍板的决策/项目契约踩坑，只在单一项目语境有用）→ route=project（宿主直写该项目工作区 docs/devref/shoucang/）",
  "- R4 其余（一次性进度/可搜索公开知识/无实质/<relevant-memories>注入缓存/重复已有归属）→ route=discard",
  "- 同一条既像 R1/R2 又像 R3：跨项目可复用→memory；只在单一项目成立→project。既不跨项目也不属于当前会话项目→丢弃。",
  "- 拿不准 → route=memory 但 appends 留空记 skipped（宁缺毋滥）。",
  "route=memory 时续走四问（**降级为归属子判据组**，不再是全局判据抬头）：Q0 已有归属？Q1 下周用得上？Q2 归谁（notes 记忆 / USER 用户画像 / AGENT 自我画像）？Q3 能合并？",
  "Q2 画像判定：**用户的稳定偏好/背景/禁忌**（非一次性需求）→ profiles target=USER.md；**agent 自身的稳定做法/能力边界/常犯错误教训**（可跨任务复用的自我认知）→ profiles target=AGENT.md；一般知识→appends。",
  "规则/纪律/程序类：**不入库**（SKILL 与 skill 协议文档是随插件发布的只读文档，无写入通道；v2 删除原「规则→SOUL.md」死支）。",
].join('\n')

/** 巩固域判据段（拼进 DEEP_SLEEP_PROMPT） */
export const CONSOLIDATE_JUDGE = [
  "- **原则判据**：同主题 ≥3 条痕迹，或单主题当日反复命中 → 提炼 1 条原则；支撑不足的一律不提炼（路径判据见下，二者区分勿混）。",
  "- 原则=一句方向指引（泛化度=方向指引，目标形态/步骤轮廓/关键注意点），不搬细节条文。",
  "- **路径判据**：同一任务类型在窗口内出现 ≥2 次（痕迹/运行统计可见重复模式）→ 归纳 1 条路径；候选区若含「成功次数 ≥2 且跨会话 ≥2」的任务候选 = 已达转正门槛（memory-core-model §4），直接归纳为 [路径]；**只归纳成功走通的任务**，失败任务只进原则教训（AWM：只从成功学）。",
  "- **跨工作区红线**：记忆库是全局单库，痕迹可能来自多个工作区，而原则会常驻注入到**所有**工作区会话。含项目专名/具体路径/版本号/一次性事实的经验一律不提炼（skipped 注明「项目专属」）；只在单一项目语境成立的结论同样不提炼——宁缺毋滥，误注入比漏提炼危害大。",
  "- **前提识别（premise awareness，v2 新增判据）**：提炼出的原则/路径若依赖某个**未写出的隐含前提**（特定工具链/特定环境/特定阶段），必须在概况或小节正文里写出该前提；写不出就降级为 notes 事实，不升格。",
  "- **v19 跨日二次激活**：材料「近 7 日再现」给出被**再次命中**的已有条目——同一条目在多个日窗重现 = 该主题稳固，可经 pointerOps 扩容概况或提纯为更高层原则；只在单日出现的不要当稳固信号。",
].join('\n')

export const JUDGEMENT_HINT = "judgement：可选对象，把本次判据取值写进输出（reuse/generality/stability/conflict/dup 或 evidence/stability/conflict/cost；取值见 criteria 注册表），宿主据此写 judgement-ledger 供对账。"
export const LEDGER_FILE = "audit/judgement-ledger.jsonl"

export const L0 = {
  "reuse": {
    "values": [
      "cross-task",
      "cross-project",
      "session-only"
    ],
    "text": "可复用性：跨任务 / 跨项目 / 仅本会话"
  },
  "generality": {
    "values": [
      "direction",
      "contract-fact",
      "detail"
    ],
    "text": "泛化度：方向指引（粗）/ 契约事实 / 细节条文"
  },
  "stability": {
    "values": [
      "once",
      "same-day-repeat",
      "cross-day"
    ],
    "text": "稳定性：单次 / 当日重现 / 跨日或多会话重现"
  },
  "conflict": {
    "values": [
      "none",
      "coexist",
      "supersede"
    ],
    "text": "冲突性：无 / 与既有并存 / 取代既有"
  }
} as const

export const GATE = {
  "caps": {
    "MEMORY.md": 5000,
    "USER.md": 3000,
    "AGENT.md": 3000
  },
  "notesWarn": 8000,
  "budgetFormula": {
    "lineChars": 100,
    "fixed": 56,
    "pointer": 44
  },
  "exit": {
    "capacity": 1,
    "pointer": 2,
    "format": 4
  },
  "envOverride": {
    "MEMORY.md": "SHOUCANG_CAP_MEMORY",
    "USER.md": "SHOUCANG_CAP_USER",
    "AGENT.md": "SHOUCANG_CAP_AGENT"
  }
} as const

export const HEALTH = {
  "R": 1000,
  "K": 6,
  "notesWarn": 8000,
  "checks": [
    "capacity",
    "duplicates",
    "tags",
    "pointers",
    "section-existence",
    "index-ledger-coverage",
    "inject-token-account",
    "placement-audit"
  ]
} as const

export const SURFACE = {
  "injection": {
    "budgetChars": 3000,
    "order": 88,
    "relevance": true,
    "freshSlots": 2,
    "levelCaps": {
      "low": 2,
      "medium": 4,
      "high": 8,
      "smart": 10
    }
  },
  "recall": {
    "topK": 3,
    "topKMax": 5,
    "scope": "all",
    "coldFactorPercent": 35
  },
  "fusion": {
    "kind": "rrf",
    "k": 60,
    "fallback": "weighted",
    "weights": {
      "dense": 0.7,
      "lexical": 0.3
    },
    "dedupBySection": true
  },
  "threshold": {
    "metric": "abs-cosine",
    "tOn": 0.65,
    "tOff": 0.6,
    "note": "ACT-024 校准：绝对余弦；归一化融合分只能排序不可做阈值"
  },
  "rerank": {
    "enabled": false,
    "gate": {
      "indexRows": 200,
      "followRateDropRuns": 2
    },
    "note": "触发门未达前不引入 reranker（避免堆叠）"
  },
  "mcl": {
    "familiarThreshold": 0.65,
    "maxNudges": 1,
    "budgetChars": 600,
    "topK": 3
  }
} as const

export const CRITERIA_ROWS = [
  {
    "id": "ingest.route.r1",
    "domain": "ingest",
    "kind": "soft",
    "text": "R1 泛化方向指引 → memory",
    "params": {
      "route": "memory"
    }
  },
  {
    "id": "ingest.route.r2",
    "domain": "ingest",
    "kind": "soft",
    "text": "R2 跨项目细粒度条文 → memory(notes/tools|lessons)",
    "params": {
      "route": "memory"
    }
  },
  {
    "id": "ingest.route.r3",
    "domain": "ingest",
    "kind": "soft",
    "text": "R3 项目专属事实 → project（直写工作区）",
    "params": {
      "route": "project",
      "target": "<workspace>/docs/devref/shoucang/"
    }
  },
  {
    "id": "ingest.route.r4",
    "domain": "ingest",
    "kind": "soft",
    "text": "R4 其余 → discard",
    "params": {
      "route": "discard"
    }
  },
  {
    "id": "ingest.route.q0",
    "domain": "ingest",
    "kind": "soft",
    "text": "Q0 已有归属 → 不存",
    "params": {}
  },
  {
    "id": "ingest.route.q1",
    "domain": "ingest",
    "kind": "soft",
    "text": "Q1 下周用不上 → 不存",
    "params": {}
  },
  {
    "id": "ingest.route.q2",
    "domain": "ingest",
    "kind": "soft",
    "text": "Q2 归谁（用户/agent/环境）",
    "params": {
      "targets": [
        "notes",
        "USER.md",
        "AGENT.md"
      ]
    }
  },
  {
    "id": "ingest.route.q3",
    "domain": "ingest",
    "kind": "soft",
    "text": "Q3 能合并 → replace 否则 add",
    "params": {}
  },
  {
    "id": "ingest.route.rules-not-stored",
    "domain": "ingest",
    "kind": "soft",
    "text": "规则类不入库（SOUL 死支已删）",
    "params": {
      "reason": "rules-not-stored"
    }
  },
  {
    "id": "ingest.placement.notes-kind",
    "domain": "ingest",
    "kind": "hard",
    "text": "落点须在 notes 白名单内",
    "params": {
      "notes": [
        "env",
        "tools",
        "flows",
        "lessons",
        "release",
        "user",
        "agent"
      ]
    }
  },
  {
    "id": "ingest.placement.main-index",
    "domain": "ingest",
    "kind": "hard",
    "text": "主索引写入仅三主档",
    "params": {
      "indexTargets": [
        "MEMORY.md",
        "USER.md",
        "AGENT.md"
      ]
    }
  },
  {
    "id": "ingest.granularity.split-law",
    "domain": "ingest",
    "kind": "hard",
    "text": "子树正文 > R 或同级条目 > K → 裂 ###（§8.1 分裂律）",
    "params": {
      "R": 1000,
      "K": 6
    }
  },
  {
    "id": "ingest.dedup.exact",
    "domain": "ingest",
    "kind": "hard",
    "text": "同 标签+主题 精确重复 → 拒收",
    "params": {
      "enabled": true
    }
  },
  {
    "id": "ingest.dedup.bigram",
    "domain": "ingest",
    "kind": "hard",
    "text": "主题 bigram 重叠 ≥ 阈值 → 近似重复拒收",
    "params": {
      "threshold": 0.66,
      "minTokens": 2
    }
  },
  {
    "id": "ingest.format.index-line",
    "domain": "ingest",
    "kind": "hard",
    "text": "索引行四要素格式（spec §8）",
    "params": {
      "topicMax": 12,
      "summaryMax": 30,
      "pathSummaryMax": 40,
      "banDate": true,
      "requirePointer": true,
      "requireMiddleDot": true,
      "forbidArrowInPath": true
    }
  },
  {
    "id": "consolidate.support.principle",
    "domain": "consolidate",
    "kind": "soft",
    "text": "原则：同主题 ≥3 条痕迹（或当日反复命中）",
    "params": {
      "minTraces": 3
    }
  },
  {
    "id": "consolidate.support.path",
    "domain": "consolidate",
    "kind": "soft",
    "text": "路径：同型 ≥2 次且只从成功任务归纳",
    "params": {
      "minOccur": 2,
      "crossSessionMin": 2,
      "successOnly": true
    }
  },
  {
    "id": "consolidate.promote.premise",
    "domain": "consolidate",
    "kind": "soft",
    "text": "涉及隐含前提 → 必须写出，否则降级 notes",
    "params": {
      "requirePremiseWhenDependent": true
    }
  },
  {
    "id": "consolidate.cross-workspace-redline",
    "domain": "consolidate",
    "kind": "soft",
    "text": "跨工作区红线：项目专名/路径/版本号不提炼",
    "params": {
      "forbidProjectNames": true
    }
  },
  {
    "id": "consolidate.reshape.split-law",
    "domain": "consolidate",
    "kind": "hard",
    "text": "treeOps split：正文 > R 且 ≥2 语义正交子面",
    "params": {
      "R": 1000,
      "K": 6,
      "partsMax": 6,
      "minParts": 2
    }
  },
  {
    "id": "consolidate.demote.archive",
    "domain": "consolidate",
    "kind": "hard",
    "text": "遗忘：cold 且 ≥90 天 + 三守卫；禁直删；画像节禁归档",
    "params": {
      "coldDays": 90,
      "guards": [
        "leaf",
        "cold-or-retired",
        "not-stub"
      ],
      "profileFilesForbidden": true,
      "maxPerRun": 3,
      "allowDelete": false
    }
  },
  {
    "id": "consolidate.cross.crossTopic",
    "domain": "consolidate",
    "kind": "hard",
    "text": "REM 相：crossTopic 源指针须覆盖 ≥2 个不同 §",
    "params": {
      "minSections": 2
    }
  },
  {
    "id": "consolidate.replay.cross-day",
    "domain": "consolidate",
    "kind": "soft",
    "text": "跨日二次激活：近 7 日再现 → 可扩容/提纯",
    "params": {
      "windowDays": 7
    }
  },
  {
    "id": "consolidate.pointer.update-only",
    "domain": "consolidate",
    "kind": "hard",
    "text": "pointerOps 只允许原地 update（禁增删索引行）",
    "params": {
      "allow": [
        "update"
      ],
      "forbid": [
        "add",
        "delete"
      ]
    }
  }
] as const
