// AUTO-GENERATED by scripts/gen-criteria.mjs from skill/engine/criteria.json — DO NOT EDIT.
// 判据唯一事实源 = skill/engine/criteria.json；改判据请改注册表后重跑生成器（scripts/check-criteria.mjs 机检一致）。

export const CRITERIA_VERSION = "v2.2.0"

/** 摄取域判据段（拼进 DEFAULT_DISTILL_PROMPT） */
export const INGEST_JUDGE = [
  "第一层归属路由（对每条候选按序判定）：",
  "- R1 泛化方向指引？这条知识的作用=下次做类似任务给大概方向？→ route=memory（粗粒度是特性，不要把细节条文塞进记忆库）",
  "- R2 官方规范/平台规则/工具用法等**跨项目有用**的细粒度条文 → route=memory（归 notes/tools 或 notes/lessons，教程式浓缩）",
  "- R3 某项目专属事实（项目结构/该项目用户拍板的决策/项目契约踩坑，只在单一项目语境有用）→ route=project（宿主直写该项目工作区 docs/devref/shoucang/）",
  "- R4 其余（一次性进度/可搜索公开知识/无实质/<relevant-memories>注入缓存/重复已有归属）→ route=discard",
  "- 同一条既像 R1/R2 又像 R3：跨项目可复用→memory；只在单一项目成立→project。既不跨项目也不属于当前会话项目→丢弃。",
  "- 拿不准 → route=memory 但 appends 留空记 skipped（宁缺毋滥）。",
  "route=memory 时续走四问（**降级为归属子判据组**，不再是全局判据抬头）：Q0 已有归属？Q1 下周用得上？Q2 归谁（notes 记忆 / USER 用户画像 / AGENT 自我画像）？Q3 能合并？",
  "Q2 画像判定：**用户的稳定偏好/背景/禁忌**（非一次性需求）→ profiles target=USER.md；**agent 自身的稳定做法/能力边界/常犯错误教训/表达风格（`[性格]`）/思维模式（`[认知]`）**（可跨任务复用的自我认知）→ profiles target=AGENT.md；一般知识→appends。",
  "规则/纪律/程序类：**不入库**（SKILL 与 skill 协议文档是随插件发布的只读文档，无写入通道；v2 删除原「规则→SOUL.md」死支）。",
  "- **经历四通道（2026-09-14 · P4 新增）：与 route 无关，任何路由下都可填**——它们是「经历」而非「知识」，故不受 R1–R4 归属路由约束：`decisions`（裁决：拍了什么板 + **当时预测** `predicted`，那是日后后果回收的对照项）/ `commitments`（承诺：`who` + `what` + `direction`[owed-by-me=我欠|owed-to-me=欠我] + `due`，**形成时就要落库**——意图事后无从恢复）/ `relations`（关系事实：`who` + `note`[在意什么/忌讳什么]）/ `valences`（价态：`trigger`[在什么情境下] + `valence`[+1 好 / -1 坏]）。",
  "- 四通道每条**必带 `cues`**（情境键数组，形如 `[\"scope=workspace:<路径>\",\"task=build\"]`）——它是日后「在什么情境下该想起它」的**唯一线索**；写不出情境就留**空数组**（读侧有兜底序，不会因缺 cues 而丢失，只是优先级降低）。**没有实质经历就留空数组**，不要为凑数编造；这四类与 appends/newIndex 互不替代（经历进环、知识进 notes）。",
  "- **索引行格式硬门（写门 exit=4，违反任一条即整条被拒）**：概况段普通行 ≤30 字、`[路径]` 概要 ≤40 字（超出即整条被拒）；主题段 ≤12 字（软提示，不拦截）；**`[路径]` 行的步骤内禁写 `→`**（会与 `→ notes/` 指针箭头歧义）——步骤一律用 ①②③ 串联；必须含中间点「·」分隔主题与概况；必须以 `→ notes/<文件>.md §<小节>` 结尾；概况中禁写日期戳。**若内容压不进上限：把细节写进 notes 小节，索引行只留 ≤30 字概况**——切勿硬塞长句（长句会被整条丢弃，等于白提炼）。",
].join('\n')

/** 巩固域判据段（拼进 DEEP_SLEEP_PROMPT） */
export const CONSOLIDATE_JUDGE = [
  "- **原则判据**：同主题 ≥3 条痕迹，或单主题当日反复命中 → 提炼 1 条原则；支撑不足的一律不提炼（路径判据见下，二者区分勿混）。",
  "- 原则=一句方向指引（泛化度=方向指引，目标形态/步骤轮廓/关键注意点），不搬细节条文。",
  "- **路径判据**：同一任务类型在窗口内出现 ≥2 次（痕迹/运行统计可见重复模式）→ 归纳 1 条路径；候选区若含「成功次数 ≥2 且跨会话 ≥2」的任务候选 = 已达转正门槛（memory-core-model §4），直接归纳为 [路径]；**只归纳成功走通的任务**，失败任务只进原则教训（AWM：只从成功学）。",
  "- **跨工作区红线**：记忆库是全局单库，痕迹可能来自多个工作区，而原则会常驻注入到**所有**工作区会话。含项目专名/具体路径/版本号/一次性事实的经验一律不提炼（skipped 注明「项目专属」）；只在单一项目语境成立的结论同样不提炼——宁缺毋滥，误注入比漏提炼危害大。",
  "- **前提识别（premise awareness，v2 新增判据）**：提炼出的原则/路径若依赖某个**未写出的隐含前提**（特定工具链/特定环境/特定阶段），必须在概况或小节正文里写出该前提；写不出就降级为 notes 事实，不升格。",
  "- **v19 跨日二次激活**：材料「近 7 日再现」给出被**再次命中**的已有条目——同一条目在多个日窗重现 = 该主题稳固，可经 pointerOps 扩容概况或提纯为更高层原则；只在单日出现的不要当稳固信号。",
  "- **后果回收（`outcomes`，P5 新增 · 决策环的核心）**：材料若含「待回收的裁决」（带 `decisionId` 与**当时预测**），且你从痕迹/运行统计里看得出**实际结果**，就填：`{\"decisionId\":\"decision:xxxx\",\"observed\":\"实际发生了什么\",\"hit\":true|false,\"evidence\":\"来源\"}`。**没有后果回收，经历永远只是日志**（无法校准判断力）；看不出来就留空数组，**不要猜**。重复回收会被宿主丢弃（幂等）。",
  "- **经历叙事（`narratives`，P5 新增 · author 层）**：把窗口内「决定过什么 → 后来怎样」串成 **1–3 段带时间的因果短叙事**（**不是流水账、不是原则**）：`{\"title\":\"≤40字\",\"text\":\"≤400字，写清前因—决断—后果\",\"cues\":[\"scope=workspace:<路径>\"],\"evidence\":\"来源\"}`。正文落 `notes/agent.md §经历/<title>`，宿主另生 `episode` 记录（指针指回该小节）。**宁少勿编**：没有真正连成故事的经历就留空数组。",
  "- **索引行格式硬门（写门 exit=4，违反任一条即整条被拒）**：概况段普通行 ≤30 字、`[路径]` 概要 ≤40 字（超出即整条被拒）；主题段 ≤12 字（软提示，不拦截）；**`[路径]` 行的步骤内禁写 `→`**（会与 `→ notes/` 指针箭头歧义）——步骤一律用 ①②③ 串联；必须含中间点「·」分隔主题与概况；必须以 `→ notes/<文件>.md §<小节>` 结尾；概况中禁写日期戳。**若内容压不进上限：把细节写进 notes 小节，索引行只留 ≤30 字概况**——切勿硬塞长句（长句会被整条丢弃，等于白提炼）。",
].join('\n')

export const JUDGEMENT_HINT = "judgement：可选对象，把本次判据取值写进输出（reuse/generality/stability/conflict/dup 或 evidence/stability/conflict/cost；取值见 criteria 注册表），宿主据此写统一台账 audit/ledger.jsonl（type=decision.*）供对账。"
export const LEDGER_FILE = "audit/ledger.jsonl"

export const L0 = {
  "reuse": {
    "values": [
      "cross-task",
      "cross-project",
      "session-only"
    ],
    "text": "可复用性：跨任务 / 跨项目 / 仅本会话"
  },
  "generality": {
    "values": [
      "direction",
      "contract-fact",
      "detail"
    ],
    "text": "泛化度：方向指引（粗）/ 契约事实 / 细节条文"
  },
  "stability": {
    "values": [
      "once",
      "same-day-repeat",
      "cross-day"
    ],
    "text": "稳定性：单次 / 当日重现 / 跨日或多会话重现"
  },
  "conflict": {
    "values": [
      "none",
      "coexist",
      "supersede"
    ],
    "text": "冲突性：无 / 与既有并存 / 取代既有"
  }
} as const

export const GATE = {
  "caps": {
    "MEMORY.md": 5000,
    "USER.md": 3000,
    "AGENT.md": 3000
  },
  "notesWarn": 8000,
  "budgetFormula": {
    "lineChars": 100,
    "fixed": 56,
    "pointer": 44
  },
  "exit": {
    "capacity": 1,
    "pointer": 2,
    "format": 4
  },
  "envOverride": {
    "MEMORY.md": "SHOUCANG_CAP_MEMORY",
    "USER.md": "SHOUCANG_CAP_USER",
    "AGENT.md": "SHOUCANG_CAP_AGENT"
  }
} as const

export const HEALTH = {
  "R": 1000,
  "K": 6,
  "notesWarn": 8000,
  "checks": [
    "capacity",
    "duplicates",
    "tags",
    "pointers",
    "section-existence",
    "index-ledger-coverage",
    "inject-token-account",
    "placement-audit"
  ]
} as const

export const SURFACE = {
  "injection": {
    "budgetChars": 4000,
    "budgetNote": "热记忆注入**恒定面安全带**（字符）。语义（2026-09-13 v2 修正）：恒定面（双画像索引行 + P 层画像行）**必在、不按比例裁**，本值只防库无界膨胀；变动面（知识索引）≤600、一次性面（成长 delta）≤200 各有硬顶，超预算的行被裁且**留痕提示**（不静默）。测算：AGENT 索引 1,138 + USER 索引 430 + 画像行 ≈630 + 标题 ≈1,990 ⇒ 实际每步 ≈2,800 上限。原 1800（三层按比例分档）会把 AGENT 侧 `[原则]`/`[路径]` 裁掉一半以上、损伤人格一致性，已回退该口径。**⚠ 2026-09-14（P8 收口 · 实测否决）**：P8 原计划「恒定面**框架化**」（把清单降为「框架 + 可展开指针」）**经实测否决，不再重议**——测得每步真实 **2391–2977 字符**（Q1），其中 P 层 **1756 字符**，而 **`[原则]`+`[路径]` = 1532 字符（87%）且 18 条互不重复**（画像行与索引行**同名重复 = 0**）；**可压面只剩指针尾巴 302 字符（≈总 10%）**，而压缩会把 `notes/lessons.md §X` 变成缩写 ⇒ **引入新的指针解析失败模式**（与「模型须能按指针取详情」及 L2「误注入代价 > 漏注入」冲突）。⇒ 结论：**无既定的可收益压缩面**；恒定面之所以大，是因为它**几乎全是承载人格的习得原则**，而不是「灌」。要再压须先改变「原则不得裁」这条口径本身（那是一条已拍板的价值选择，不在本方案范围内）。",
    "order": 88,
    "relevance": true,
    "freshSlots": 2,
    "levelCaps": {
      "low": 2,
      "medium": 4,
      "high": 8,
      "smart": 10
    },
    "carriers": {
      "profile": 6,
      "note": "P 层画像行注入上限（0=关闭 → 回滚到「画像行不注入」的旧行为）。沿革：2026-09-13（P0）3→4（配额改「按标签各留最近 1 条」）；同日 4→6（质量评估 R3）：实测被挡下的画像行 agent 3 条 / user 13–14 条，其中有「架构议题要抛开历史决策约束…」「UI 判定须视觉实证」等高价值偏好——提到 6（zod 上限）以减少「最有用的那几条恰好被挡」的概率；仍受稳定面安全带与块内配额约束，被挡者留痕可见。上限可配 injectProfileRows（0–6）"
    },
    "situation": {
      "enabled": true,
      "budgetChars": 300,
      "cueDims": [
        "scope",
        "task",
        "subject",
        "event"
      ],
      "ringOrder": [
        "relation",
        "decision",
        "association",
        "fact",
        "value"
      ],
      "topN": 3,
      "note": "**情境层（第三槽）**：环记录（`file=''`，无 md 投影）不进内容相关性面，而由**情境键匹配**（cue-driven）供给——依据是编码特异性（提取取决于「编码情境↔提取线索」匹配，非内容相似度）与前瞻记忆多进程框架（承诺/意图须线索驱动，纯战略监控在高负荷下系统性失败）。enabled=false 且 budgetChars=0 ⇒ **缺省零行为变化**（照抄 serendipity 槽先例）。cueDims 是**唯一维度声明处**（situation-key.ts 按它迭代，不另立名单）；ringOrder 按**环**排序（commitment 与 relation 同属 relation 环；episode 属 fact 环——故不按 kind 排，避免把两个语义层混进一张表）。**2026-09-14 P7 订正**：原先把 `value` 环排除在外，理由是「走图式层」——但图式层走的是 **md 投影行**，而 `valence` 记录是 `file=''` 的**环记录** ⇒ 实测它**两条路都不可达**（既不在恒定面、也不在 ringOrder）。现把 `value` 补进 ringOrder **末位**：只有 `file=''` 的 value 环记录（即 valence；`persona`/`principle`/`preference` 皆带 md 投影或不产出）能进，故不会挤占。**同时放弃原计划的 `alphaVal` 打分项**：`layeredScore` 的打分对象是**索引行**，索引行**没有 valence 信号**（valence 只存在于环记录 meta）⇒ 加它只能是恒 0 的**假旋钮**（仓内警示的「假可控」）。valence 的正确定位是**情境召回**，不是相关性权重。",
      "adaptive": true,
      "adaptiveNote": "S4-5（2026-09-14）：`true` ⇒ 情境槽 `topN` 由**活体环记录数**派生（clamp(ceil(√N),3,12)，实测 N=105 ⇒ 11）；`false` ⇒ 回退固定 `topN`。判因：固定 3 而库内环记录 105 条 ⇒ 命中率天花板 ≈3%，\"库越大经历面越稀释\"。"
    },
    "process": {
      "enabled": false,
      "carrierTag": [
        "路径"
      ],
      "topN": 3,
      "budgetChars": 300,
      "note": "S4-3（2026-09-14）**中层 process 槽**：任务级供给 —— 按标签取 `[路径]` 行（**不走内容相关性竞争**）。判因：人类三层结构里**中层是唯一没有专用通路的层**（`[路径]` 现经 R 层 gated 相关性召回，与其它内容争同一预算；且实测库内 `[路径]` 仅 5 条）。缺省 `enabled:false` ⇒ **零行为变化**。⚠ **运行时实现被前置重构阻塞**（登记 S4-findings 的 L5）：`panel-shared.ts` 受 `check-module-growth` **大模块冻结棘轮**约束（基线 831 / 上限 846），接入需先做「**动态面选行领域拆分**」—— 把该模块 :582-622 那段（预热缓存 ∪ 相关性 ∪ 新鲜槽 ∪ 基线补位）抽成独立模块（净减约 35 行），才腾得出接入空间。**那一步是本领的前置，不是可选项。**"
    }
  },
  "score": {
    "mode": "v2",
    "alphaRel": 1,
    "alphaImp": 0.25,
    "alphaRec": 0.1,
    "note": "v2.2 统一打分：score = α_rel·relevance(RRF) + α_imp·importance + α_rec·recency。**α_imp=0.25 由模拟证据选定**（scripts/shadow-sim.mjs 扫描：α=0.35→top-3 Jaccard 0.56 扰动过大；α=0.25→0.68 满足预注册判据 Jaccard≥0.6，且 corr(imp,rel)=−0.293 证明分量不冗余、扰动方向为『换进更重要条目』）。**mode=v2 已于 2026-09-11 翻转**（运行时开关 scheduler.scoreWeights=v2 同步）；回滚 = 两处同时回 legacy"
  },
  "recall": {
    "topK": 3,
    "topKMax": 5,
    "scope": "all",
    "coldFactorPercent": 35
  },
  "fusion": {
    "kind": "rrf",
    "k": 60,
    "fallback": "weighted",
    "weights": {
      "dense": 0.7,
      "lexical": 0.3
    },
    "dedupBySection": true
  },
  "threshold": {
    "metric": "abs-cosine",
    "tOn": 0.65,
    "tOff": 0.6,
    "note": "ACT-024 校准：绝对余弦；归一化融合分只能排序不可做阈值"
  },
  "rerank": {
    "enabled": false,
    "gate": {
      "indexRows": 200,
      "followRateDropRuns": 2
    },
    "note": "触发门未达前不引入 reranker（避免堆叠）"
  },
  "mcl": {
    "familiarThreshold": 0.55,
    "maxNudges": 1,
    "budgetChars": 600,
    "topK": 3,
    "note": "2026-09-11 阈值重校准（缺陷2）：旧值 0.65 在实测样本上**结构性不可达**——193 条 mcl-step 审计 sim 分布 max=0.634 / mean=0.5658 / p75=0.609 / p90=0.624，≥0.65 命中 **0 行** ⇒ 快通道恒为 0（快/慢分流退化为单一慢通道）。**2026-09-14 P7 二次重校准（D3）**：在 **936 条** sim 样本上按**预注册判据**（目标覆盖率 = 注册表原始意图 27.5%）取分位——实测 p50=0.513 / p60=0.529 / p70=0.548 / p72.5=0.548 / **p75=0.561** / p90=0.575 / max=0.662；扫阈值得 0.54→38.9% · **0.55→25.4%** · 0.56→25.1% · 0.57→11.9% · 0.58→**9.3%**（= 上轮值，实测远低于其自述的 27.5%）。取 **0.55**（最接近 27.5% 且落在拐点上）。回滚：**/set mclFamiliarThreshold 0.58**（全局 scheduler.json，热生效，无需重启）。**另一道门 hasHighConf 未放宽**（仍要求 mclGate 标签），故实际快通道触发率显著低于 25.4%。"
  }
} as const

export const CARRIERS = {
  "note": "载体契约（v2.2 · ADR-130）：每个标签声明 layer（生效层）+ form（存在形式）+ inject（可注入性）。P 层 always（恒常、不参与相关性竞争）；R/E 层 gated（按任务型/相关性调用）；notes/audit 为 none。读取面必须实现每种 injectable 载体的渲染器（机检 scripts/check-carriers.mjs）。",
  "tags": {
    "身份": {
      "layer": "P",
      "form": "index",
      "inject": "always"
    },
    "使命": {
      "layer": "P",
      "form": "index",
      "inject": "always"
    },
    "边界": {
      "layer": "P",
      "form": "profile",
      "inject": "always"
    },
    "性格": {
      "layer": "P",
      "form": "profile",
      "inject": "always",
      "new": true
    },
    "认知": {
      "layer": "P",
      "form": "profile",
      "inject": "always",
      "new": true
    },
    "演化": {
      "layer": "P",
      "form": "index",
      "inject": "always"
    },
    "偏好": {
      "layer": "P",
      "form": "index",
      "inject": "always"
    },
    "习惯": {
      "layer": "P",
      "form": "index",
      "inject": "always"
    },
    "原则": {
      "layer": "P",
      "form": "index",
      "inject": "always",
      "mclGate": true,
      "note": "仅跨环境稳定者；带情境前提者交深睡按 A≥gate 决定是否升 P。mclGate=true：命中即计 MCL 快通道「高置信」（2026-09-11 自 mcl.ts 硬编码正则归还注册表）"
    },
    "经验": {
      "layer": "E",
      "form": "index",
      "inject": "gated",
      "note": "v2.2 D7 修正：情境经验属经验层，不再当 always-on"
    },
    "教训": {
      "layer": "E",
      "form": "index",
      "inject": "gated",
      "note": "体检脚本 AGENT 侧既有标签（agent 教训≈lesson），一并登记"
    },
    "路径": {
      "layer": "R",
      "form": "index",
      "inject": "gated",
      "mclGate": true,
      "note": "任务型门控（复用 ACT-029 MCL 快通道熟悉度分流）。mclGate=true：命中即计 MCL 快通道「高置信」（2026-09-11 自 mcl.ts 硬编码正则归还注册表）"
    },
    "env": {
      "layer": "E",
      "form": "index",
      "inject": "gated"
    },
    "tool": {
      "layer": "E",
      "form": "index",
      "inject": "gated"
    },
    "flow": {
      "layer": "E",
      "form": "index",
      "inject": "gated"
    },
    "lesson": {
      "layer": "E",
      "form": "index",
      "inject": "gated"
    },
    "环境": {
      "layer": "P",
      "form": "index",
      "inject": "always",
      "note": "USER 侧：用户环境构成"
    },
    "硬件": {
      "layer": "P",
      "form": "index",
      "inject": "always"
    }
  },
  "renderers": {
    "always:index": "src/panel.ts#readCarrier（索引行 always 全量按档位 cap）",
    "always:profile": "src/panel.ts#readCarrier（画像行 `- … ← 源:` ≤ injection.carriers.profile 条/档；P 层 profile 标签由注册表驱动）",
    "gated:index": "src/targets.ts#recallIndex + src/vec.ts#recallRanked（相关性/任务型门控）",
    "none:notes": "src/panel.ts#/memory/sections（按需读取，不注入）",
    "none:audit": "scripts/criteria-audit.mjs（只读审计，不注入）"
  }
} as const

export const SCORE = {
  "mode": "v2",
  "alphaRel": 1,
  "alphaImp": 0.25,
  "alphaRec": 0.1,
  "note": "v2.2 统一打分：score = α_rel·relevance(RRF) + α_imp·importance + α_rec·recency。**α_imp=0.25 由模拟证据选定**（scripts/shadow-sim.mjs 扫描：α=0.35→top-3 Jaccard 0.56 扰动过大；α=0.25→0.68 满足预注册判据 Jaccard≥0.6，且 corr(imp,rel)=−0.293 证明分量不冗余、扰动方向为『换进更重要条目』）。**mode=v2 已于 2026-09-11 翻转**（运行时开关 scheduler.scoreWeights=v2 同步）；回滚 = 两处同时回 legacy"
} as const

export const MATURATION = {
  "A0": 0.3,
  "step": 0.2,
  "gate": 0.5,
  "enforce": false,
  "note": "成熟度（v2.2 E6）：A(0)=A0；每次跨日再现 +step（上限 1.0）；只有 A≥gate 才允许升格为 [原则]/[路径]；A<gate 不注入但参与打分（implicit priming）。enforce=false 时只记录不强制（M4 影子期）。**2026-09-14（P7 · D11）决策：保持 false，并把依据写在这里**——`maturation-scan` 实测**拦阻率 57.4% > 50%**，扫描器自己的判据是「翻 enforce 会**冻结升格**」⇒ 当前不可翻。**记录该决策的目的**：把 `false` 从「疑似遗漏的开关」变成「**有实测依据的选择**」，后来人不必重查。要翻转须先让拦阻率降到 50% 以下（信号源=activity.days30 / access.log 的观测窗口仍在积累）",
  "ledger": "audit/maturation.jsonl"
} as const

export const TRIGGER = {
  "idleMs": 2700000,
  "probeAfterMs": 2700000,
  "probeWindowMs": 60000,
  "newTracesMin": 1,
  "manual": true,
  "note": "触发数据化（v2.1 §2.4 · B 档接线后为 runtime）：idleMs=全部根会话停滞阈值（缺省 3h）；probeAfterMs/probeWindowMs=卡住探测；newTracesMin=窗口内最少新痕迹数；manual=面板「立即归纳一次」。**改这里即改行为**（scheduler zod 缺省直接读本块）。"
} as const

export const WIRING: { note: string; why: string; entryOk: readonly string[]; typeOnlyOk: readonly string[]; pending: ReadonlyArray<{ name: string; until: string; reason?: string }>; pendingNote?: string } = {
  "note": "接线申报（2026-09-14 · 治「结构合法但运行时缺席」）。判据：`src/` 内扇入 0 的模块 = 没有运行时消费者，必须显式申报；落地后不删即 FAIL（棘轮）。判定实现在 scripts/audit-architecture.mjs（`--gate` 时生效，check-runner 已在跑该模式）。**只看 src/ 运行时消费者**：scripts/ 下的离线工具与单测一律不算（否则离线工具会让门白立）。",
  "why": "本仓 7 件架构机检全是负面约束（无环/无桥/行数/依赖宽度/符号漂移），没有一道问「这个模块有没有人在用」。实测后果：supply-assembly 与 record-address 功能完整、结构合法、单测全绿，但 src/ 内零消费者 —— 唯一消费者是离线 CLI 与单测。审计脚本**早已算出扇入**，只是只打印不判定。**2026-09-14 两件均已结清**：`supply-assembly` 已接线（P0a）；`record-address` **判定为死件并删除** —— 它服务的 `storeMode='record'` 档被 schema **明确拒收**（`z.union([const('md'), const('dual')])`，其注释原文：「'record' 档（md 降为纯投影）**尚未实现** ⇒ 本键不接受该值（防死开关）」），且两条配置通道（Config schema · `applySuiteConfigFile` 的派生白名单 + 逐键过 schema）都挡住它 ⇒ 该件**永无运行时接线的可能**，保留即纯堆叠。",
  "entryOk": [
    "index",
    "panel"
  ],
  "typeOnlyOk": [
    "deepsleep-contract"
  ],
  "pending": [],
  "pendingNote": "**零豁免（2026-09-14 起）**：本表为空 ⇒ 任何模块只要 `src/` 扇入为 0 且不在 entryOk / typeOnlyOk，接线门**当场 FAIL**。这是接线门的**最紧状态**，也是本表存在的意义（棘轮只许收紧）；将来若确需豁免，必须在此显式加回并写明 `until`。"
}

export const CRITERIA_ROWS = [
  {
    "id": "ingest.route.r1",
    "domain": "ingest",
    "kind": "soft",
    "text": "R1 泛化方向指引 → memory",
    "params": {
      "route": "memory"
    }
  },
  {
    "id": "ingest.route.r2",
    "domain": "ingest",
    "kind": "soft",
    "text": "R2 跨项目细粒度条文 → memory(notes/tools|lessons)",
    "params": {
      "route": "memory"
    }
  },
  {
    "id": "ingest.route.r3",
    "domain": "ingest",
    "kind": "soft",
    "text": "R3 项目专属事实 → project（直写工作区）",
    "params": {
      "route": "project",
      "target": "<workspace>/docs/devref/shoucang/"
    }
  },
  {
    "id": "ingest.route.r4",
    "domain": "ingest",
    "kind": "soft",
    "text": "R4 其余 → discard",
    "params": {
      "route": "discard"
    }
  },
  {
    "id": "ingest.route.q0",
    "domain": "ingest",
    "kind": "soft",
    "text": "Q0 已有归属 → 不存",
    "params": {}
  },
  {
    "id": "ingest.route.q1",
    "domain": "ingest",
    "kind": "soft",
    "text": "Q1 下周用不上 → 不存",
    "params": {}
  },
  {
    "id": "ingest.route.q2",
    "domain": "ingest",
    "kind": "soft",
    "text": "Q2 归谁（用户/agent/环境）",
    "params": {
      "targets": [
        "notes",
        "USER.md",
        "AGENT.md"
      ]
    }
  },
  {
    "id": "ingest.route.q3",
    "domain": "ingest",
    "kind": "soft",
    "text": "Q3 能合并 → replace 否则 add",
    "params": {}
  },
  {
    "id": "ingest.route.rules-not-stored",
    "domain": "ingest",
    "kind": "soft",
    "text": "规则类不入库（SOUL 死支已删）",
    "params": {
      "reason": "rules-not-stored"
    }
  },
  {
    "id": "ingest.placement.notes-kind",
    "domain": "ingest",
    "kind": "hard",
    "text": "落点须在 notes 白名单内",
    "params": {
      "notes": [
        "env",
        "tools",
        "flows",
        "lessons",
        "release",
        "user",
        "agent"
      ]
    }
  },
  {
    "id": "ingest.placement.main-index",
    "domain": "ingest",
    "kind": "hard",
    "text": "主索引写入仅三主档",
    "params": {
      "indexTargets": [
        "MEMORY.md",
        "USER.md",
        "AGENT.md"
      ]
    }
  },
  {
    "id": "ingest.granularity.split-law",
    "domain": "ingest",
    "kind": "hard",
    "text": "子树正文 > R 或同级条目 > K → 裂 ###（§8.1 分裂律）",
    "params": {
      "R": 1000,
      "K": 6
    }
  },
  {
    "id": "ingest.dedup.exact",
    "domain": "ingest",
    "kind": "hard",
    "text": "同 标签+主题 精确重复 → 拒收",
    "params": {
      "enabled": true
    }
  },
  {
    "id": "ingest.dedup.bigram",
    "domain": "ingest",
    "kind": "hard",
    "text": "主题 bigram 重叠 ≥ 阈值 → 近似重复拒收",
    "params": {
      "threshold": 0.66,
      "minTokens": 2
    }
  },
  {
    "id": "ingest.format.index-line",
    "domain": "ingest",
    "kind": "hard",
    "text": "索引行四要素格式（spec §8）",
    "params": {
      "topicMax": 12,
      "summaryMax": 30,
      "pathSummaryMax": 40,
      "banDate": true,
      "requirePointer": true,
      "requireMiddleDot": true,
      "forbidArrowInPath": true,
      "note": "**实测根因（2026-09-11）**：写门曾硬编码 30/40 而 prompt 未携带该约束 ⇒ 深睡产出普遍超标被逐条拦掉（attempted=3 → all-rejected，概况 31/38/36 字）。现：门读投影 + 生成器把约束派生进两个判据段。"
    }
  },
  {
    "id": "consolidate.support.principle",
    "domain": "consolidate",
    "kind": "soft",
    "text": "原则：同主题 ≥3 条痕迹（或当日反复命中）",
    "params": {
      "minTraces": 3
    }
  },
  {
    "id": "consolidate.support.path",
    "domain": "consolidate",
    "kind": "soft",
    "text": "路径：同型 ≥2 次且只从成功任务归纳",
    "params": {
      "minOccur": 2,
      "crossSessionMin": 2,
      "successOnly": true
    }
  },
  {
    "id": "consolidate.promote.premise",
    "domain": "consolidate",
    "kind": "soft",
    "text": "涉及隐含前提 → 必须写出，否则降级 notes",
    "params": {
      "requirePremiseWhenDependent": true
    }
  },
  {
    "id": "consolidate.cross-workspace-redline",
    "domain": "consolidate",
    "kind": "soft",
    "text": "跨工作区红线：项目专名/路径/版本号不提炼",
    "params": {
      "forbidProjectNames": true
    }
  },
  {
    "id": "consolidate.reshape.split-law",
    "domain": "consolidate",
    "kind": "hard",
    "text": "treeOps split：正文 > R 且 ≥2 语义正交子面",
    "params": {
      "R": 1000,
      "K": 6,
      "partsMax": 6,
      "minParts": 2
    }
  },
  {
    "id": "consolidate.demote.archive",
    "domain": "consolidate",
    "kind": "hard",
    "text": "遗忘：cold 且 ≥90 天 + 三守卫；禁直删；画像节禁归档",
    "params": {
      "coldDays": 90,
      "guards": [
        "leaf",
        "cold-or-retired",
        "not-stub"
      ],
      "profileFilesForbidden": true,
      "maxPerRun": 3,
      "allowDelete": false
    }
  },
  {
    "id": "consolidate.cross.crossTopic",
    "domain": "consolidate",
    "kind": "hard",
    "text": "REM 相：crossTopic 源指针须覆盖 ≥2 个不同 §",
    "params": {
      "minSections": 2
    }
  },
  {
    "id": "consolidate.replay.cross-day",
    "domain": "consolidate",
    "kind": "soft",
    "text": "跨日二次激活：近 7 日再现 → 可扩容/提纯",
    "params": {
      "windowDays": 7
    }
  },
  {
    "id": "consolidate.pointer.update-only",
    "domain": "consolidate",
    "kind": "hard",
    "text": "pointerOps 只允许原地 update（禁增删索引行）",
    "params": {
      "allow": [
        "update"
      ],
      "forbid": [
        "add",
        "delete"
      ]
    }
  }
] as const

export interface ContentTypeConsumer { layer: string; timing: string; criterion: string }
export interface ContentType {
  recordKind: string[]
  carrier: string[]
  form: string
  producers: string[]
  projection: string
  consumer: ContentTypeConsumer
  budget: string
  reachable: boolean
  why?: string
}
export interface ContentTypeStructural { projection: string; consumer: ContentTypeConsumer; budget: string; reachable?: boolean; why?: string }
export const CONTENT_TYPES: { note?: string; types: Record<string, ContentType>; structural: Record<string, ContentTypeStructural> } = {
  "types": {
    "principle": {
      "recordKind": [
        "persona"
      ],
      "carrier": [
        "原则"
      ],
      "form": "profile",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "md",
      "consumer": {
        "layer": "outer",
        "timing": "session-start",
        "criterion": "always"
      },
      "budget": "stable",
      "reachable": true
    },
    "cognition": {
      "recordKind": [
        "persona"
      ],
      "carrier": [
        "认知"
      ],
      "form": "profile",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "md",
      "consumer": {
        "layer": "outer",
        "timing": "session-start",
        "criterion": "always"
      },
      "budget": "stable",
      "reachable": true
    },
    "boundary": {
      "recordKind": [
        "persona"
      ],
      "carrier": [
        "边界"
      ],
      "form": "profile",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "md",
      "consumer": {
        "layer": "outer",
        "timing": "session-start",
        "criterion": "always"
      },
      "budget": "stable",
      "reachable": true
    },
    "evolution": {
      "recordKind": [
        "persona"
      ],
      "carrier": [
        "演化"
      ],
      "form": "index",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "md",
      "consumer": {
        "layer": "outer",
        "timing": "session-start",
        "criterion": "always"
      },
      "budget": "stable",
      "reachable": true
    },
    "identity": {
      "recordKind": [
        "persona"
      ],
      "carrier": [
        "身份"
      ],
      "form": "index",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "md",
      "consumer": {
        "layer": "outer",
        "timing": "session-start",
        "criterion": "always"
      },
      "budget": "stable",
      "reachable": true
    },
    "mission": {
      "recordKind": [
        "persona"
      ],
      "carrier": [
        "使命"
      ],
      "form": "index",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "md",
      "consumer": {
        "layer": "outer",
        "timing": "session-start",
        "criterion": "always"
      },
      "budget": "stable",
      "reachable": true
    },
    "character": {
      "recordKind": [
        "persona"
      ],
      "carrier": [
        "性格"
      ],
      "form": "profile",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "md",
      "consumer": {
        "layer": "outer",
        "timing": "session-start",
        "criterion": "always"
      },
      "budget": "stable",
      "reachable": true
    },
    "preference": {
      "recordKind": [
        "persona"
      ],
      "carrier": [
        "偏好"
      ],
      "form": "index",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "md",
      "consumer": {
        "layer": "outer",
        "timing": "session-start",
        "criterion": "always"
      },
      "budget": "stable",
      "reachable": true
    },
    "habit": {
      "recordKind": [
        "persona"
      ],
      "carrier": [
        "习惯"
      ],
      "form": "index",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "md",
      "consumer": {
        "layer": "outer",
        "timing": "session-start",
        "criterion": "always"
      },
      "budget": "stable",
      "reachable": true
    },
    "environment": {
      "recordKind": [
        "persona"
      ],
      "carrier": [
        "环境"
      ],
      "form": "index",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "md",
      "consumer": {
        "layer": "outer",
        "timing": "session-start",
        "criterion": "always"
      },
      "budget": "stable",
      "reachable": true
    },
    "hardware": {
      "recordKind": [
        "persona"
      ],
      "carrier": [
        "硬件"
      ],
      "form": "index",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "md",
      "consumer": {
        "layer": "outer",
        "timing": "session-start",
        "criterion": "always"
      },
      "budget": "stable",
      "reachable": true
    },
    "path": {
      "recordKind": [
        "procedure"
      ],
      "carrier": [
        "路径"
      ],
      "form": "index",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "md",
      "consumer": {
        "layer": "middle",
        "timing": "task-start",
        "criterion": "relevance"
      },
      "budget": "dynamic",
      "reachable": true,
      "why": "中层独立 process 槽为 S4-3 目标；当前实际经相关性召回（R 层 gated，不进恒常面）"
    },
    "experience": {
      "recordKind": [
        "fact"
      ],
      "carrier": [
        "经验"
      ],
      "form": "index",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "md",
      "consumer": {
        "layer": "inner",
        "timing": "on-demand",
        "criterion": "relevance"
      },
      "budget": "dynamic",
      "reachable": true
    },
    "lessonTag": {
      "recordKind": [
        "fact"
      ],
      "carrier": [
        "教训"
      ],
      "form": "index",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "md",
      "consumer": {
        "layer": "inner",
        "timing": "on-demand",
        "criterion": "relevance"
      },
      "budget": "dynamic",
      "reachable": true
    },
    "env": {
      "recordKind": [
        "fact"
      ],
      "carrier": [
        "env"
      ],
      "form": "index",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "md",
      "consumer": {
        "layer": "inner",
        "timing": "on-demand",
        "criterion": "relevance"
      },
      "budget": "dynamic",
      "reachable": true
    },
    "tool": {
      "recordKind": [
        "fact"
      ],
      "carrier": [
        "tool"
      ],
      "form": "index",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "md",
      "consumer": {
        "layer": "inner",
        "timing": "on-demand",
        "criterion": "relevance"
      },
      "budget": "dynamic",
      "reachable": true
    },
    "flow": {
      "recordKind": [
        "fact"
      ],
      "carrier": [
        "flow"
      ],
      "form": "index",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "md",
      "consumer": {
        "layer": "inner",
        "timing": "on-demand",
        "criterion": "relevance"
      },
      "budget": "dynamic",
      "reachable": true
    },
    "lesson": {
      "recordKind": [
        "fact"
      ],
      "carrier": [
        "lesson"
      ],
      "form": "index",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "md",
      "consumer": {
        "layer": "inner",
        "timing": "on-demand",
        "criterion": "relevance"
      },
      "budget": "dynamic",
      "reachable": true
    },
    "episode": {
      "recordKind": [
        "episode"
      ],
      "carrier": [],
      "form": "ring",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "none",
      "consumer": {
        "layer": "inner",
        "timing": "per-step",
        "criterion": "situation-key"
      },
      "budget": "situation",
      "reachable": true
    },
    "decision": {
      "recordKind": [
        "decision"
      ],
      "carrier": [],
      "form": "ring",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "none",
      "consumer": {
        "layer": "inner",
        "timing": "per-step",
        "criterion": "situation-key"
      },
      "budget": "situation",
      "reachable": true
    },
    "outcome": {
      "recordKind": [
        "outcome"
      ],
      "carrier": [],
      "form": "ring",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "none",
      "consumer": {
        "layer": "inner",
        "timing": "per-step",
        "criterion": "situation-key"
      },
      "budget": "situation",
      "reachable": true
    },
    "valence": {
      "recordKind": [
        "valence"
      ],
      "carrier": [],
      "form": "ring",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "none",
      "consumer": {
        "layer": "inner",
        "timing": "per-step",
        "criterion": "situation-key"
      },
      "budget": "situation",
      "reachable": true
    },
    "relation": {
      "recordKind": [
        "relation"
      ],
      "carrier": [],
      "form": "ring",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "none",
      "consumer": {
        "layer": "inner",
        "timing": "per-step",
        "criterion": "situation-key"
      },
      "budget": "situation",
      "reachable": true
    },
    "commitment": {
      "recordKind": [
        "commitment"
      ],
      "carrier": [],
      "form": "ring",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "none",
      "consumer": {
        "layer": "middle",
        "timing": "on-demand",
        "criterion": "situation-key"
      },
      "budget": "situation",
      "reachable": true,
      "why": "到期前瞻（due 主动提）为 S4-4 目标；当前实际经情境槽进入（commitment 属 relation 环）"
    },
    "association": {
      "recordKind": [
        "association"
      ],
      "carrier": [],
      "form": "ring",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "none",
      "consumer": {
        "layer": "inner",
        "timing": "per-step",
        "criterion": "situation-key"
      },
      "budget": "situation",
      "reachable": true
    },
    "noteBody": {
      "recordKind": [
        "prose"
      ],
      "carrier": [],
      "form": "notes",
      "producers": [
        "distill",
        "deepsleep"
      ],
      "projection": "md",
      "consumer": {
        "layer": "inner",
        "timing": "on-demand",
        "criterion": "none"
      },
      "budget": "none",
      "reachable": true,
      "why": "详情层正文（notes/*.md）：**不直接注入**，经索引行指针按需 read_section 取 ⇒ criterion=none（无自动注入通路，故无通道即正确）。S2-2 补：writeDispatch 的 appends 路径输出它，此前契约无 form=notes 的 typeId 承载"
    }
  },
  "structural": {
    "blank": {
      "projection": "none",
      "consumer": {
        "layer": "none",
        "timing": "none",
        "criterion": "none"
      },
      "budget": "none",
      "reachable": false,
      "why": "空行，无信息内容"
    },
    "structure": {
      "projection": "none",
      "consumer": {
        "layer": "none",
        "timing": "none",
        "criterion": "none"
      },
      "budget": "none",
      "reachable": false,
      "why": "标题/引用等结构行，不注入"
    },
    "prose": {
      "projection": "md",
      "consumer": {
        "layer": "inner",
        "timing": "on-demand",
        "criterion": "relevance"
      },
      "budget": "dynamic",
      "reachable": true
    }
  }
}
